---
layout: cv
title: Samuel Cruz's Resume
---
# Samuel Cruz
Business Analyst.

<div id="webaddress">
<a href="samuellucas.rr@gmail.com">samuellucas.rr@gmail.com</a>
| <a href="https://www.linkedin.com/in/cruzsamuel/">My LinkdIN page</a>
</div>

## Skills
| Excel, Pivotable, Macros | Teamwork   |
| Time Management          | Python     |
| Problem-solving          | Tableau    |
| Analythical Thinkng      | MySQL      |
| Product Management       | SharePoint |
| TeamDynamix              | PowerBI    |
| Communication            | Leadership |


## Professional Experience
__IT Business Analyst Lead__ `04/2025 - Present`
*Brigham Young University - Idaho* 
- Lead a team of 4 employees, providing guidance, training, and supervision for task completion and adherence to deadlines.
- Develop and analyze multiple Power BI dashboards, providing actionable insights for decision-making on various topics.
- Collaborated with cross-functional teams to identify key performance metrics and KPIs, helping streamline data collection processes and improve overall data quality for enhanced reporting accuracy.

__IT Data Analyst__ `04/2024 - 04/2025`
*Brigham Young University - Idaho*
- Improved visibility into IT operations across BYU-Idaho collaborating with the CIO and IT Directors to
develop a Power BI dashboard by integrating data from TeamDynamix, SQL, and Microsoft Excel,
improving visibility into IT operations.
- Achieved a 70% improvement in SLA compliance rates by managing and tracking IT service tickets
through the PowerBI dashboard ensuring timely resolution.
- Monitored customer satisfaction metrics to identify trends, potential issues, and actionable solutions,
enhancing service delivery quality, improving decision-making, and operational efficiency.
- Conduct detailed audits of financial reports to ensure accuracy and compliance in the recording of
purchased receipts.

__Electrical Technician Intern__ `03/2018 - 01/2019`
*Roraima Energia*
- Operated the AJURI system, a database with service order management, equipment management, billing
measurement, collection, and inspection with around 197 thousand registered consumer units.
- Analyzed data using Excel to make data-driven decisions for improvements.
- Updated over 1500 consumer units that had incorrect information using QGIS and Ajuri software
database, increasing productivity in other departments at the company

## Education
__Bachelor of Science in Business Analytics__ `04/2027 - Anticipated Graduation`
*Brigham Young University - Idaho*
- GPA 3.96
  
__Spreadsheet Analysis for Business__
Learned skills in Microsoft Excel such as budgeting, asset management, and financial analysis using
advanced formulas, Pivot tables, and Macros.
__Microsoft Excel Project:__  Reduced 900 hours of academic planning for the Federal Institute of Roraima's
department chairs by developing a dashboard with conditional formatting, data validation, countifs
functions, macros, and a database for curricular components according to the code associated with each
one via lookup functions.
 

## Volunteer Experience
__Full-time Volunteer__ `03/2021 - 03/2023 | Santos, Brazil`
*The Church of Jesus Christ of Latter-day Saints*
- Responsible for motivating, evaluating, reporting the progress of, and caring for 24 volunteers.
- Trained a group of 100+ volunteers on setting more effective goals as a group, and how to achieve success
through it.

<!-- ### Footer

Last updated: Apr 2025 -->